# Minimal MoveIt controller mapping for ros2_control.
#
# If you are not using MoveIt, this file is harmless. It is installed because
# `setup.py` expects it.
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rotating_base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gripper_joint

